---
apiVersion: v1
kind: Service
metadata:
  name: teddy
  labels:
    app: teddy
spec:
  type: NodePort
  selector:
    app: teddy
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: teddy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: teddy
    spec:
      containers:
      - name: teddy
        image: lingxizhixia/teddy:1.0
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1