apiVersion: v1
kind: ReplicationController
metadata:
  name: teddy2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: teddy2
    spec:
      containers:
      - name: teddy2
        image: lingxizhixia/teddy:1.0
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1