apiVersion: v1
kind: Pod
metadata:
  name: teddy4
spec:
  containers:
  - name: teddy3
    image: lingxizhixia/teddy:1.0
    ports:
    - containerPort: 8010
    - hostPort: 8010
    livenessProbe:
      httpGet:
        path: /health
        port: 8010
      initialDelaySeconds: 30
      timeoutSeconds: 1