apiVersion: v1
kind: Service
metadata:
  name: teddy4
  labels:
    app: teddy4
spec:
  type: NodePort
  selector:
    app: teddy4
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
    name: http