apiVersion: v1
kind: Pod
metadata:
   name: teddy5
   labels:
     name: teddy5
spec:
  containers:
  - name: teddy5
    image: lingxizhixia/teddy:1.0
    ports:
    - containerPort: 8010
      hostPort: 8010