apiVersion: v1
kind: ReplicationController
metadata:
  name: teddy5
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: teddy5
    spec:
      containers:
      - name: teddy5
        image: lingxizhixia/teddy:1.0
        ports:
        - containerPort: 8010