apiVersion: v1
kind: Service
metadata:
  name: teddy5
  labels:
    app: teddy5
spec:
  type: NodePort
  selector:
    app: teddy5
  ports:
  - protocol: TCP
    port: 8010
    nodePort: 8010
    name: http