apiVersion: v1
kind: Pod
metadata:
   name: teddy4
   labels:
     name: teddy4
spec:
  containers:
  - name: teddy4
    image: lingxizhixia/teddy:1.0
    ports:
    - containerPort: 8010
      hostPort: 8010